### ISSUE TITLE
provide Ratelimiter type aliases?

### ISSUE THREAD

**Issue by gdesmott** [antifuchs/nonzero_ext#22]
Because of all the generics, storing a limiter in a `struct` is a bit verbose:

```rust
    cover_limiter: governor::RateLimiter<
        governor::state::NotKeyed,
        governor::state::InMemoryState,
        governor::clock::DefaultClock,
        governor::middleware::NoOpMiddleware,
    >,
```

Maybe we could type aliases for the common types like the one returned by `RateLimiter::direct()`?

**Comment by antifuchs** [comment]
Argh, yes, we need that in governor. I think you got the wrong repo, though: We're tracking it in https://github.com/antifuchs/governor/issues/85.

**Comment by gdesmott** [comment]
Oups, sorry, my bad :)

**Comment by antifuchs** [comment]
If you can make the time, I'd super appreciate a pull request - I'm currently traveling but should be able to review one in a few days; otherwise, it'll take me a few weeks to get back into more OSS work /:
